_wandb:
    value:
        cli_version: 0.22.3
        e:
            5872ojknw3ub2tp40xf0r074jnxv2z37:
                codePath: scripts/sft.py
                codePathLocal: scripts/sft.py
                email: jennybenarye@gmail.com
                executable: /opt/anaconda3/envs/arena/bin/python
                git:
                    commit: 4030d0faeaadbec3b597263b3f9523436981df9c
                    remote: https://github.com/jenbenarye/adversarial-rlhf.git
                host: dhcp-10-31-186-26.dyn.MIT.EDU
                os: macOS-26.0.1-arm64-arm-64bit
                program: /Users/jenbenarye/Desktop/Projects/adversarial-rlhf/scripts/sft.py
                python: CPython 3.12.12
                root: /Users/jenbenarye/Desktop/Projects/adversarial-rlhf
                startedAt: "2025-11-02T02:23:22.961891Z"
                writerId: 5872ojknw3ub2tp40xf0r074jnxv2z37
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 71
                - 84
                - 98
            "2":
                - 1
                - 11
                - 49
                - 51
                - 71
                - 84
                - 98
            "3":
                - 16
            "4": 3.12.12
            "5": 0.22.3
            "6": 4.57.1
            "12": 0.22.3
            "13": darwin-arm64
model:
    value:
        dtype: bfloat16
        model_name_or_path: teknium/OpenHermes-2.5-Mistral-7B
script:
    value:
        dataset_name: HuggingFaceH4/ultrafeedback_binarized
        dataset_streaming: true
        dataset_test_split: test_sft
        dataset_train_split: train_sft
training:
    value:
        bf16: true
        eval_steps: 100
        eval_strategy: steps
        gradient_accumulation_steps: 8
        gradient_checkpointing: false
        learning_rate: 2e-05
        logging_steps: 5
        max_length: 4096
        num_train_epochs: 1
        output_dir: data/2.5-Mistral-7B-SFT
        packing: null
        per_device_train_batch_size: 2
        report_to:
            - wandb
        run_name: sft
